# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      # specify the version
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/yunify/terraform-provider-qingcloud
    steps:
      - checkout
      - run: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - run: sudo apt-get install nodejs
      - run: sudo npm install -g codeclimate-test-reporter
      - run: |
                 shopt -s globstar;
                 rootdir=`pwd`;

                 for dir in $(go list ./... |grep -v 'vendor'); do
                   cd $GOPATH/src/$dir;
                   exec 5>&1;
                   out=$(TF_ACC=1 go test -timeout 120m -v -coverprofile=cov_part.out | tee >(cat - >&5))
                   if [ $? -eq 1 ] ; then
                     if [ $(cat $out | grep -o 'no buildable Go source files') == "" ] ; then
                       echo "Tests failed! Exiting..." ; exit 1
                     fi
                     if [cat $out | grep -q "FAIL"] ; then
                       echo "Tests failed! Exiting..." ; exit 1
                     fi
                   fi
                   cd $rootdir
                 done

                 if [ -z "$CI_NAME" ]; then
                   echo "CI_NAME is unset. Skipping coverage report!"
                   exit 0
                 fi

                 find . -name cov_part.out | xargs cat > cov.out
                 codeclimate-test-reporter < cov.out
  release:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/runzexia/circleci-ghr
    steps:
      - checkout
      - run: git config --global user.name runzexia
      - run: make dist
      - run: make release

workflows:
  version: 2
  test_release:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
